// <auto-generated />
using System;
using Algara.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Algara.Web.ShopMigrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260410133336_AddSubCategories")]
    partial class AddSubCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Algara.Data.Models.Category", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("N");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.HeroSlide", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N"));

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ButtonUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EyebrowText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("N");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_HeroSlides_Active_Order");

                    b.ToTable("HeroSlides", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.Order", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserN")
                        .HasColumnType("int");

                    b.HasKey("N");

                    b.HasIndex(new[] { "UserN" }, "IX_Orders_UserN");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N"));

                    b.Property<int>("OrderN")
                        .HasColumnType("int");

                    b.Property<int>("ProductN")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("N");

                    b.HasIndex("OrderN");

                    b.HasIndex("ProductN");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.Product", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N"));

                    b.Property<int?>("CategoryN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("N");

                    b.HasIndex("CategoryN");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.ProductSubCategory", b =>
                {
                    b.Property<int>("ProductN")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryN")
                        .HasColumnType("int");

                    b.HasKey("ProductN", "SubCategoryN");

                    b.HasIndex("SubCategoryN");

                    b.ToTable("ProductSubCategories", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.SubCategory", b =>
                {
                    b.Property<int>("N")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N"));

                    b.Property<int>("CategoryN")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("N");

                    b.HasIndex("CategoryN");

                    b.ToTable("SubCategories", (string)null);
                });

            modelBuilder.Entity("Algara.Data.Models.OrderItem", b =>
                {
                    b.HasOne("Algara.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algara.Data.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Algara.Data.Models.Product", b =>
                {
                    b.HasOne("Algara.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryN")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Algara.Data.Models.ProductSubCategory", b =>
                {
                    b.HasOne("Algara.Data.Models.Product", "Product")
                        .WithMany("ProductSubCategories")
                        .HasForeignKey("ProductN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Algara.Data.Models.SubCategory", "SubCategory")
                        .WithMany("ProductSubCategories")
                        .HasForeignKey("SubCategoryN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Algara.Data.Models.SubCategory", b =>
                {
                    b.HasOne("Algara.Data.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Algara.Data.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Algara.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Algara.Data.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductSubCategories");
                });

            modelBuilder.Entity("Algara.Data.Models.SubCategory", b =>
                {
                    b.Navigation("ProductSubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
